In [3]:
import cv2
img = cv2.imread('ColorChecker1.jpg')
# cv2.imshow('img', img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [4]:
img.shape

(297, 441, 3)

In [5]:
def ResizeWithAspectRatio(image, width=None, height=None, inter=cv2.INTER_AREA):
    dim = None
    (h, w) = image.shape[:2]

    if width is None and height is None:
        return image
    if width is None:
        r = height / float(h)
        dim = (int(w * r), height)
    else:
        r = width / float(w)
        dim = (width, int(h * r))

    return cv2.resize(image, dim, interpolation=inter)

def getROIposition(img):
    resize = ResizeWithAspectRatio(img, width=600) # Resize by width OR
    scale = img.shape[0] / resize.shape[0]

    roi = cv2.selectROI(windowName="roi", img=resize, showCrosshair=False, fromCenter=False)
    roi = list(map(lambda x: int(x * scale), roi))
#     x, y, w, h = roi

    # cv2.imshow("roi", img[y : y+h, x:x+w])
    # cv2.waitKey(0)
    cv2.destroyAllWindows()
    return roi

In [62]:
img = cv2.imread('ColorChecker1.jpg')
x, y, w, h = getROIposition(img)
img = img[y:y+h, x:x+w]
h, w, c = img.shape
color = (0, 0, 255) # red
thickness = 2 # 寬度 (-1 表示填滿)
square = 0.08*w
padding = 0.087*w

start_h = 0.044*w
for i in range(4):
    start_w = 0.044*w
    for j in range(6):
        patch = img[int(start_h):int(start_h+square), int(start_w):int(start_w+square)]
        cv2.imshow('patch', patch)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
#         cv2.rectangle(img, (int(start_w), int(start_h)), (int(start_w+square), int(start_h+square)), color, thickness)
        start_w+=(square+padding)
    start_h+=(square+padding)
    
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [54]:
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [59]:
img[:,:,0].shape

(283, 431)

In [51]:
import numpy as np
def signaltonoise(a):
    a = np.asanyarray(a)
    m = a.mean()
    sd = a.std()
    return m/sd


In [52]:
signaltonoise(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY))

2.261484349573313

In [64]:
np.log10(0.3)

-0.5228787452803376

In [67]:
a1 = np.array([[1,2],[3,4]])
a1

array([[1, 2],
       [3, 4]])

In [68]:
a2 = np.array([[2,3],[1,0]])
a2

array([[2, 3],
       [1, 0]])

In [77]:
a = [a1, a2]
a

[array([[1, 2],
        [3, 4]]),
 array([[2, 3],
        [1, 0]])]

In [78]:
np.max(a,axis=0)

array([[2, 3],
       [3, 4]])

In [87]:
max_idx = np.where(a1==np.max(a,axis=0))
c1[max_idx] = 'g'
c1

array([['N', 'N'],
       ['g', 'g']], dtype='<U1')

In [85]:
c1 = np.array([['N']*2]*2)
c1

array([['N', 'N'],
       ['N', 'N']], dtype='<U1')

In [73]:
a1[a1<a2]

array([1, 2])

In [72]:
c1[a1<a2] = 'r'
c1

TypeError: only integer scalar arrays can be converted to a scalar index